### ISSUE TITLE
connection from RSclient over TLS fails in RS.auth()

### ISSUE THREAD

**Issue by thrubovc** [s-u/Rserve#92] opened 2017-11-30 09:48 UTC
I am having an issue, where I connect to Rserv from RSclient and the connection doesn't work 95% of the time, when making a TLS connection. It literally fails most of the time and >sometimes< it just works.
however, when I make a connection without TLS, it works every time.

> con <- RS.connect(host = "127.0.0.1", port = 4445, tls = TRUE)
> RS.login(con, user = "myRserveUserName", password="myRservePW", authkey=RS.authkey(con))
rsc_abort: read error
Error in RS.authkey(con) : read error - could not obtain response header

meanwhile, in the RServe console I get this error:
`Error: ignoring SIGPIPE signal`
`Fatal error: unable to initialize the JIT`

I would appreciate any ideas. Thanks.

**Comment by thrubovc** [comment] 2017-11-30 13:31
I'm attaching the code from Rserv.dbg mode from both successful and unsuccessful connection attempt for comparison.

successful:
```
header read result: 16
DUMP [16]: 06 00 00 00 10 00 00 00 00 00 00 00 00 00 00 00  |................
loading buffer (awaiting 16 bytes)
parsing parameters (buf=0x26009a0, len=16)
DUMP [16]: 04 0c 00 00 72 73 61 2d 61 75 74 68 6b 65 79 00  |....rsa-authkey.
PAR[0]: 00000010 (PAR_LEN=12, PAR_TYPE=4, large=no, c=0x26009a0, ptr=0x26009a4)
CMD=00000006, pars=1
rsa_gen_resp: generating RSA key
 - done
OUT.sendRespData
HEAD DUMP [16]: 01 00 01 00 16 04 00 00 00 00 00 00 00 00 00 00  |................
BODY DUMP [1046]: 00 02 00 00 be a0 21 59 6b d7 e6 2b e6 ba 4f 74 1f 56 0d 7a ca d1 1e a8 b0 41 aa 51 00 6c 59 4d 41 6d 78 e3 0a 57 12 71 4c 54 11 d9 90 ff e6 02 a3 10 f4 05 07 e5 16 7e f6 92 1f 8f a7 24 dc dd 21 ce ee 0f 48 50 21 49 96 7a 90 a6 e9 07 3d 82 8f c9 6e bd 48 6c ff 5e 95 f0 31 17 27 51 fc 9d a0 de 8a ad b6 86 6c 93 57 d5 ba 9e 6e 84 1c 6e 89 6e 59 a0 7f 61 11 e6 de b4 28 91 1a cf 75 ef b5 ...  |......!Yk..+..Ot.V.z.....A.Q.lYMAmx..W.qLT.............~.....$..!...HP!I.z....=...n.Hl.^..1.'Q........l.W...n..n.nYa....(...u..

header read result: 16
DUMP [16]: 07 00 00 00 04 04 00 00 00 00 00 00 00 00 00 00  |................
loading buffer (awaiting 1028 bytes)
parsing parameters (buf=0x26009a0, len=1028)
DUMP [1028]: 05 00 04 00 5b 25 46 3a 5d 10 73 bd 6d 26 25 9c f3 d8 fc 2e b5 66 60 0d df ef 1e f1 6b fd 34 4d cf e7 dc 1f e9 86 29 1e dc 5a 37 a5 cb e5 ba ac a2 4a 25 33 5a c8 0c 99 3a 70 0c bf 27 29 49 e9 d8 45 91 7e 24 f7 a9 1e a8 d6 e2 7a 6a c3 b4 7e 39 88 2f c3 3c 76 ae 18 18 40 97 f2 25 0d 54 0d 3c 2d 04 26 aa a5 26 17 f8 07 d3 b7 66 62 a2 30 67 0c 5b 5f 1f ad 8a 56 95 1e ce d9 88 71 b5 1f f1 ...  |....[%F:].s.m&%......f`.....k.4M......)..Z7......J%3Z...:p..')I..E.~$......zj..~9./.<v...@..%.T.<-.&..&.....fb.0g.[_...V.....q...
PAR[0]: 00000404 (PAR_LEN=1024, PAR_TYPE=5, large=no, c=0x26009a0, ptr=0x26009a4)
CMD=00000007, pars=1
CMD_secLogin: authkey matches, asl payload: 29
Authentication attempt (login='myRserveUserName', pwd='myRservePW', pwdfile='/home/ruser/passwordfile')
Found login 'myRserveUserName', checking password.
 - stored pwd = 'myRservePW', md5='6afd010f823cab1a660340a4e5cf8be1', sha1='0fa67f16ecc11bac749d22f208f44bba45b7d37f'
 - plain password matches.
OUT.sendRespData
HEAD DUMP [16]: 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00  |................
(no body)
```

unsuccessful:
```
header read result: 16
DUMP [16]: 06 00 00 00 10 00 00 00 00 00 00 00 00 00 00 00  |................
loading buffer (awaiting 16 bytes)
parsing parameters (buf=0x26009a0, len=16)
DUMP [16]: 04 0c 00 00 72 73 61 2d 61 75 74 68 6b 65 79 00  |....rsa-authkey.
PAR[0]: 00000010 (PAR_LEN=12, PAR_TYPE=4, large=no, c=0x26009a0, ptr=0x26009a4)
CMD=00000006, pars=1
rsa_gen_resp: generating RSA key
 - done
OUT.sendRespData
HEAD DUMP [16]: 01 00 01 00 16 04 00 00 00 00 00 00 00 00 00 00  |................
BODY DUMP [1046]: 00 02 00 00 57 29 22 3d f1 dc 27 dc bf 7b ff a7 c4 4c ba 46 de 42 cf 39 fd d5 a9 58 c1 fe 31 9b 95 79 23 48 67 4d 26 15 66 60 74 8f 50 48 1d a5 c5 cb c9 7b ef 32 cb a1 4e 4a 49 63 d4 45 3b b5 e2 58 a9 dc 5b 74 ef 99 b9 8c df 81 f1 bb 5d 99 17 d7 ef 35 02 05 f7 93 91 2c 4d 0d 38 d1 d2 e0 e2 14 4d c8 1b bf 22 a4 1d e0 54 11 4e e4 ad 4b 7b 5b af c7 e6 c2 d7 1b 31 d5 3b 0b 40 4a b2 d2 72 ...  |....W)"=..'..{...L.F.B.9...X..1..y#HgM&.f`t.PH.....{.2..NJIc.E;..X..[t........]....5.....,M.8.....M..."...T.N..K{[......1.;.@J..r
Error: ignoring SIGPIPE signal
Fatal error: unable to initialize the JIT
```

**Comment by rchailan** [comment] 2019-07-24 15:30
@thrubovc, Did you find any fix on it? 
Two years later, I got something close to this behaviour, with quite the same ratio of successful connections.

Without changing anything from the RServe or from the RSclient command, I got two kind of responses, 
either unsuccessful 
```R
> conn <- RS.connect(host="xxxxxxxxx", port = xxxx, tls=TRUE) ; RS.login(conn, user = "xxxx", password = "xxxxxx", authkey = RS.authkey(conn))
rsc_abort: read error
Error in RS.authkey(conn) : read error - could not obtain response header
```
or successful
```R
> conn <- RS.connect(host="xxxxxxxxx", port = xxxx, tls=TRUE) ; RS.login(conn, user = "xxxx", password = "xxxxxx", authkey = RS.authkey(conn))
[1] TRUE
```

Here are the `Rserve.debug` outputs for both outputs.

unsuccessful
```sh
INFO: accepted connection for server 0x23a57c0, calling connected
connection accepted.
sending ID string.

header read result: 16
DUMP [16]: 06 00 00 00 10 00 00 00 00 00 00 00 00 00 00 00  |................
loading buffer (awaiting 16 bytes)
parsing parameters (buf=0x3d09b80, len=16)
DUMP [16]: 04 0c 00 00 72 73 61 2d 61 75 74 68 6b 65 79 00  |....rsa-authkey.
PAR[0]: 00000010 (PAR_LEN=12, PAR_TYPE=4, large=no, c=0x3d09b80, ptr=0x3d09b84)
CMD=00000006, pars=1
rsa_gen_resp: generating RSA key
 - done
OUT.sendRespData
HEAD DUMP [16]: 01 00 01 00 16 04 00 00 00 00 00 00 00 00 00 00  |................
BODY DUMP [1046]: 00 02 00 00 89 56 97 e3 8a 7f 37 e4 05 09 7b 4d 76 55 dc ce a8 1a e1 19 e3 79 80 32 29 01 64 96 5f 75 9e a7 4c b2 41 29 fd 67 95 f5 a7 bb 84 23 66 ee c9 02 3c 98 79 41 9e 1e 55 52 a9 e4 63 8c fe f1 8f e5 ae d6 dd 95 9b e5 c7 81 c9 90 d9 ed 4b 08 36 ad 41 b4 96 40 da 32 76 e9 38 e6 c0 f3 ac f0 3d 9c 34 9d e1 78 d4 0d 8c f2 12 05 c2 fe cf c2 34 be d2 30 70 8c 92 91 51 fb 9f 11 fd d4 a6 ...  |.....V...7...{MvU.......y.2).d._u..L.A).g.....#f...<.yA..UR..c.................K.6.A..@.2v.8.....=.4..x..........4..0p...Q......
Connection closed by peer.
done.
```

Successful 
```sh
INFO: accepted connection for server 0x23a57c0, calling connected
connection accepted.
sending ID string.

header read result: 16
DUMP [16]: 06 00 00 00 10 00 00 00 00 00 00 00 00 00 00 00  |................
loading buffer (awaiting 16 bytes)
parsing parameters (buf=0x3d09b80, len=16)
DUMP [16]: 04 0c 00 00 72 73 61 2d 61 75 74 68 6b 65 79 00  |....rsa-authkey.
PAR[0]: 00000010 (PAR_LEN=12, PAR_TYPE=4, large=no, c=0x3d09b80, ptr=0x3d09b84)
CMD=00000006, pars=1
rsa_gen_resp: generating RSA key
 - done
OUT.sendRespData
HEAD DUMP [16]: 01 00 01 00 16 04 00 00 00 00 00 00 00 00 00 00  |................
BODY DUMP [1046]: 00 02 00 00 3c 19 c6 f5 20 14 9a f6 e6 ba 65 b6 9b 97 46 07 8a 17 5f 6b 7d 3c b5 4e b0 c6 42 2b a8 48 6a be 82 3c 03 42 e0 09 e9 95 4c ae 60 f8 1e 73 1a 1c f6 c5 3e 7e c4 b5 80 00 92 01 ff de 6f 04 6e 3b 4e 9c d7 03 a8 08 cf 15 a8 b9 6b 12 d5 d2 55 17 08 1e 36 d8 05 e7 37 f3 8c c2 d3 4f 05 0f b4 4b c6 b0 83 be 02 fc ed 3d 1d 85 55 f6 db 52 03 56 74 36 fb 2f 25 ba 06 c5 c8 7d c7 2c d4 ...  |....<... .....e...F..._k}<.N..B+.Hj..<.B....L.`..s....>~........o.n;N.........k...U...6...7....O...K.......=..U..R.Vt6./%....}.,.

header read result: 16
DUMP [16]: 07 00 00 00 04 04 00 00 00 00 00 00 00 00 00 00  |................
loading buffer (awaiting 1028 bytes)
parsing parameters (buf=0x3d09b80, len=1028)
DUMP [1028]: 05 00 04 00 3a 49 1d 93 46 3b fa 55 64 5b e9 13 76 08 1d f7 3c 40 32 06 76 0f 30 b4 be 29 33 50 f7 a7 b3 2a 2b b2 78 79 5a ec 94 8f 3e 20 a5 a6 fe 87 35 21 8a 7d 69 de d3 ff 9c 4f ec 7d df d5 1a 33 84 7b c5 4a f6 32 ca c2 cd 66 f5 4a a1 9e c6 76 2d 2b 3e dc 0c 39 28 57 f8 7a 7c 64 3d 57 55 16 6a 2b de 66 ea b7 05 4d f8 a9 d8 9f 41 c9 86 4c 3b 6c af f4 58 10 89 7b 20 76 8d 4a 01 11 38 ...  |....:I..F;.Ud[..v...<@2.v.0..)3P...*+.xyZ...> ....5!.}i....O.}...3.{.J.2...f.J...v-+>..9(W.z|d=WU.j+.f...M....A..L;l..X..{ v.J..8
PAR[0]: 00000404 (PAR_LEN=1024, PAR_TYPE=5, large=no, c=0x3d09b80, ptr=0x3d09b84)
CMD=00000007, pars=1
CMD_secLogin: authkey matches, asl payload: 21
Authentication attempt (login='xxxx', pwd='xxxxxx', pwdfile='(null)')
OUT.sendRespData
HEAD DUMP [16]: 01 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00  |................
(no body)
```

Thanks

**Comment by thrubovc** [comment] 2019-07-25 06:24
@rchailan unfortunately, no. We were using RSclient just to test the connection. We were setting up rserve for a connection to SAP HANA, which worked fine. So we never focused on solving this issue.

**Comment by rchailan** [comment] 2019-07-25 07:27
Thanks for the reply. 
I am setting it for SAP Analytics Cloud, but unfortunately it seems the connection is closed by the pair (SAC) in the same way.

**Comment by s-u** [comment] 2019-07-25 19:16
I'll have a look, but I'm wondering why would you use TLS *and* additional RSA? The RSA authentication was introduced way before there was TLS just to avoid sending clear text passwords, but it's no longer necessary since TLS is supported which is way more secure than using the RSA password handshake.

Also what should help is exactly the configuration you're using (Rserve.conf). The above only has the client side, not the actual setup. Finally, please specify the Rserve version - it should be 1.8-6 at this time.

**Comment by rchailan** [comment] 2019-07-25 21:19
To be honest, I do not know. I do understand your point... Actually I tried to follow few docs on RServe configuration for SAC and I might have ended with a bad mix of them.

Currently my Rserv.conf is as follows 

```
workdir /SAC/Rserv/workspace
passwd /etc/Ruser.txt
remote enable
auth required
plaintext disable
port 6311
maxsendbuf 0
tls.key /SAC/Rserv/CA/Rserve.key
tls.cert /SAC/Rserv/CA/Rserve.crt
tls.port 6312
qap disable 6311
gid 1500
uid 1500
```
And yes this is the Rserve 1.8-6 (from rforge.net repo and compiled on CentOS 7).

Many thanks.

**Comment by s-u** [comment] 2019-07-26 15:42
I can replicate a problem in `RS.auth()` - it's unclear as of yet whether it's an issue in `Rserve` or `RSclient` since it appears that the client closes the connection before the server can send anything - so I'm leaning towards `RSclient` issue but I'll have to dig deeper. So for now just don't use `RS.auth()` with TLS - it's superfluous in that case anyway.

**Comment by s-u** [comment] 2019-07-26 16:07
I can confirm that this is an issue in `RSclient` - I have filed it as https://github.com/s-u/RSclient/issues/5

**Closed by s-u** 2019-07-26 16:07 UTC
