### ISSUE TITLE
Errors in loading key and certificate files fail silently

### ISSUE THREAD

**Issue by ericedelman-gh** [s-u/Rserve#160] opened 2020-09-16 14:33 UTC
When the key and certificate files specified in Rserv.conf fail to load, this does not produce any messages, only resulting in a TLS handshake failure when later trying to connect to the server.

**Comment by s-u** [comment] 2020-09-16 22:41
The proxy now handles that since 7eb30c2 so likely we should do the same for Rserve that is used without the proxy.

**Comment by ericedelman-gh** [comment] 2020-09-17 20:09
Those changes to the proxy look perfect, it would be great to have the same functionality for the main Rserve. Thanks so much.

**Comment by s-u** [comment] 2021-07-15 00:34
This should now be addressed by efff0e3
For compatibility is just a warning. Part of the issue is that TLS initialization is de-centralized in Rserve, so the validity is not actually checked until a connection is initiated.

**Closed by s-u** 2021-07-15 00:34 UTC
